version: '3.7'

services:

    
    web:
        build: .
        environment:
            - FLASK_APP=run.py

        command: flask run --host=0.0.0.0 --port=8080
        volumes:

          - .:/url-shortener

        ports:

          - 8080:8080

        depends_on:
            - db

    db:
        image: postgres:11

        environment:
            - "POSTGRES_HOST_AUTH_METHOD=trust"    
        volumes:
            - postgres_data:/var/lib/postgresql/data/

volumes:
    postgres_data:
        
